### ISSUE TITLE
No Module "evaluation_functions" in evaluation folder

### ISSUE THREAD

**Issue by Qin-Yi-Zhang** [MWod/SEGA_MW_2023#2]
While running the code, I noticed that the **evaluation_functions** code is missing in the https://github.com/MWod/SEGA_MW_2023/tree/main/src/evaluation folder. This absence is causing the model to malfunction. I am not sure if this issue is due to a problem with my download or a display error.

I apologize for taking up your time with my ignorance and I look forward to your prompt response.

Best regards,

**Comment by MWod** [comment]
Thanks for pointing this out. The missing file was added.

Bests,

**Comment by Qin-Yi-Zhang** [comment]
Thanks a lot!
